# Generated by Django 5.0.2 on 2024-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basket_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='basket_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='basket_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
