# Generated by Django 5.0.2 on 2024-03-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_slug_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
        ),
    ]
