# Generated by Django 5.0.2 on 2024-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
