# Generated by Django 5.0.2 on 2024-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categories_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
