# Generated by Django 5.0.2 on 2024-02-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_categories_img'),
    ]

    operations = [
    ]
