# Generated by Django 5.0.2 on 2024-03-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=34078941, max_length=100),
            preserve_default=False,
        ),
    ]
