# Generated by Django 5.0.2 on 2024-02-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240225_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
