# Generated by Django 5.0.2 on 2024-03-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='basket_supllier',
            new_name='basket_supplier',
        ),
    ]
