# Generated by Django 5.0.2 on 2024-03-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basket_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.payment'),
        ),
    ]
