# Generated by Django 5.0.2 on 2024-03-07 16:15

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_basket_supllier_customuser_basket_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='basket_history',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=myapp.models.generate_unique_code, max_length=13, unique=True)),
                ('products_json', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('оплачен', 'оплачен'), ('не оплачен', 'не оплачен')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
