# Generated by Django 5.0.2 on 2024-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_customuser_basket_history_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен')], max_length=20),
        ),
    ]
